# Generated by Django 2.2.2 on 2019-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='depth',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='group_no',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='order_no',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
