# Generated by Django 2.2.2 on 2019-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190621_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
